name: Playwright Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Portfolio Repository
        uses: actions/checkout@v2

      - name: Checkout Playwright Tests Repository
        uses: actions/checkout@v2
        with:
          repository: radlisowski/Playwright-E2E-Automation
          path: playwright-tests

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies and Playwright
        working-directory: ./playwright-tests/  # Ensure this points to a directory
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright Tests
        working-directory: ./playwright-tests  # Adjust to ensure this path is correct
        run: npx playwright test
